import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/context/react-query-provider";
import { Header } from "@/components/header";
import { GetStartedCard } from "@/components/get-started-card";
import { TrendingCoins } from "@/components/trending-coins";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KoinX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>
          <Header />
          <main className="flex min-h-screen flex-col overflow-x-hidden bg-white-base">
            <section className="px-12 translate-x-1">
              <div className="w-full flex pt-12 h-screen flex-col lg:flex-row">
                <div className="w-2/3 bg-green-400 h-screen">{children}</div>
                <div className="w-1/3 flex flex-col gap-5 pl-5">
                  <GetStartedCard />
                  <TrendingCoins />
                </div>
              </div>
            </section>
          </main>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
